name: dailyreport
'on':
  schedule:
    - cron: 1 * * * *
jobs:
  run:
    name: Run dailyreport
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run Your Task
        run: |
          # Add your command or script to run here
          echo "Cron job executed!"
